production:
  adapter: postgresql
  encoding: unicode
  database: url_shortener_development
  pool: 5
  username: lotbud
  password: password1

development:
  adapter: postgresql
  encoding: unicode
  database: url_shortener_development
  pool: 5
  username: lotbud
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: url_shortener_test
  pool: 5
  username: lotbud
  password: password1
